### ISSUE TITLE
passlib / bcrypt error

### ISSUE THREAD

**Issue by savchenko** [pallets-eco/flask-security#1010]
Discussed at length here: https://github.com/pyca/bcrypt/issues/684

```
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/.cache/pypoetry/virtualenvs/app-d3o9zfYz-py3.11/lib/python3.11/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
```

Can we silence this at Flask-Security-Too without monkey-patching the passlib?

**Comment by jwag956** [comment]
Looks like this fork: https://pypi.org/project/libpass/ should solve our problems - I am going to wait a bit for it to settle before converting over.
