### ISSUE TITLE
Wrong module/type in the role and user table when using flask db migrate

### ISSUE THREAD

**Issue by yjcb22** [pallets-eco/flask-security#1030]
Using the default models for Role and User is generating a migration with flask_security.datastore.AsaList()  consequently SQLALchemy cannot apply the db upgrade as follows:

![image](https://github.com/user-attachments/assets/0acaade6-f6a2-482f-82cf-92fa77a01b2e)
![image](https://github.com/user-attachments/assets/4f8de980-a4f3-4008-967f-078c81bd2864)
![image](https://github.com/user-attachments/assets/106c8056-6c80-4cc2-82d6-aee52c065782)

My understanding based on the documentation is that flask_security.datastore.AsaList() is based on SQLAlchemy MutableList so it should be used as 

permissions = Column(MutableList.as_mutable(AsaList()), nullable=True)

![image](https://github.com/user-attachments/assets/90a3df0e-8862-4c2e-bbec-bc2a765b0c0f)

**Comment by yjcb22** [comment]
One quick way to fix it although probably not the best one is to import the module:

![image](https://github.com/user-attachments/assets/a6e53e9f-5f20-4f4b-8ecf-daea1679638c)

**Comment by jwag956** [comment]
Not sure why Alembic would generate that - but as Alembic suggests - change the generated code if necessary - in this case I would:

```
from flask_security import AsaList

sa.Column('permissions', AsaList(), nullable=True)
```

**Comment by yjcb22** [comment]
Thanks @jwag956 !
