### ISSUE TITLE
SECURITY_CONFIRMABLE and Confirm Password

### ISSUE THREAD

**Issue by antos07** [pallets-eco/flask-security#1043]
I suggest reconsidering #804. The solution proposed there (setting `confirm_register_form=flask_security.RegisterForm)` actually breaks the CLI, as `flask users create` relies on `confirm_register_form`. `flask_security.RegisterForm` meanwhile relies on the request context, so it's impossible to use it from CLI. And I believe it also won't pass validation anyway but I haven't checked it

**Comment by jwag956** [comment]
I'm not sure it's broken in quite the way you are describing.. did you try:
``create email1@me.com password_confirm:'battery staple' --password 'battery staple'``

**Comment by jwag956** [comment]
Ahh yes - interesting - that actually shows that in addition to the extra confirm_password field - the other difference between the 2 register paths is the 'next' parameter.

I assume that ultimately what you are looking for is a register form with CONFIRMABLE and requiring the user to type in the password twice?? 

For the CLI - I assume there is no reason to require 'password_confirm' (which is the unintended side-effect of the above form change).

**Comment by antos07** [comment]
> I assume that ultimately what you are looking for is a register form with CONFIRMABLE and requiring the user to type in the password twice??

That's right.

> For the CLI - I assume there is no reason to require 'password_confirm' (which is the unintended side-effect of the above form change).

Yes, it's already handled by the CLI (if no `--password` argument has been provided).
