### ISSUE TITLE
Quickstart for sqlalchemy lite with wrong imports

### ISSUE THREAD

**Issue by tillwenke** [pallets-eco/flask-security#1046]
see https://flask-security-too.readthedocs.io/en/stable/quickstart.html#basic-flask-sqlalchemy-lite-application

DeclarativeBase

and

FSQLALiteUserDatastore

missing

**Comment by jwag956** [comment]
To get things working - be sure to change the __tablename__ values to lower case "User"->"user" and "Role"->"role"
