### ISSUE TITLE
OAuth Providers 2FA Redirect

### ISSUE THREAD

**Issue by AI-OQC** [pallets-eco/flask-security#951]
- After OAuth login with Google, if user has 2fa enabled, it cannot redirect to a custom component. It automatically redirects to /tf-validate, which has dated UI design. Changing 'redirect_uri' does not fix this, or SECURITY_POST_OAUTH_LOGIN_VIEW, SECURITY_POST_LOGIN_VIEW. Standard login works fine and can be redirected. 
- After entering correct authentication code, there is an error "ValueError: No valid redirect URL found - configuration error". Note again this only occurs during the OAuth route, not standard login.

**Comment by jwag956** [comment]
PLease reopen if still an issue and you have a reproducable test case.

Thanks!
